const mongoose=require("mongoose")
const registerSchema=mongoose.Schema({
    Name:String,
    Email:String,
    DateOfBirth:String,
    Password:String,
    File:String,
    CartItems:[{
        ProductId:String,
        Quantity:Number,
    }],
    WishList:[{
        ProductId:String,
    }],
    BillingAddress:{
        Address:String,
        City:String,
        ZipCode:Number,
        State:String,
        Country:String
    },
    ShippingAddress:{
        Name:String,
        ContactNo:Number,
        Address:String,
        City:String,
        ZipCode:Number,
        State:String,
        Country:String
    },
    OrderHistory:[{
        OrderId:String,
        Date:Date,
        ProductId:String,
        Category:String,
        Price:Number,
        Quantity:Number,
        TotalPrice:Number,
        ShippingDetails:{
            Name:String,
            ContactNo:Number,
            Address:String,
            City:String,
            ZipCode:Number,
            State:String,
            Country:String
        },
        BillingDetails:{
            Address:String,
            City:String,
            ZipCode:Number,
            State:String,
            Country:String
        }
    }]
})
const Register=mongoose.model("Register",registerSchema)
module.exports=Register;